# Generated by Django 2.2.9 on 2020-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
